name: almatjar
description: A new dropshipping app to help young people find self-employment opportunities and earn money by selling online


publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'


dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  flutter_bloc: ^8.1.1
  shared_preferences: ^2.0.15

  firebase_core: ^2.3.0
  firebase_auth: ^4.1.4
  google_sign_in: ^5.4.2
  flutter_facebook_auth: ^5.0.6
  cloud_firestore: ^4.1.0

  flutter_svg: ^1.1.6
  animated_text_kit: ^4.2.2
  cupertino_icons: ^1.0.2



dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icons/
    - assets/images/
    - assets/svg/
    - assets/lang/en.json
    - assets/lang/ar.json

  fonts:
    - family: Raleway
      fonts:
        - asset: assets/fonts/Raleway-Regular.ttf
    - family: Loew Next Arabic
      fonts:
        - asset: assets/fonts/Loew Next Arabic.otf
